### ISSUE TITLE
/model/predict: Handle invalid input gracefully

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Audio-Embedding-Generator#5] opened 2018-07-31 18:38 UTC
API endpoint `/model/predict` returns HTTP status code 200 and

```
{
"status": "error",
"result": null
}
```

if an invalid `audio` input is provided. It should return status code 400 if an error is caused by input that cannot be processed because it doesn't meet the [stated] requirements.

**Comment by bdwyer2** [comment] 2018-09-18 22:29
Hey @ptitzler I am unable to reproduce this problem. Maybe this was fixed in a recent commit. Can you please verify?

![image](https://user-images.githubusercontent.com/19673623/45720021-856f1a80-bb57-11e8-99b8-1991960bf334.png)

**Comment by bdwyer2** [comment] 2018-09-18 22:31
Looks like Karthik fixed this in a077ba55bb65f74843c11eba8593271c9dc84944

**Closed as completed by bdwyer2** 2018-09-18 22:31 UTC
